# Generated by Django 5.2.1 on 2025-06-02 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_goal', models.CharField(choices=[('strength', 'Ganho de Força'), ('hypertrophy', 'Hipertrofia'), ('weight_loss', 'Perda de Peso'), ('neural_strength', 'Força Neural'), ('endurance', 'Resistência')], max_length=20)),
                ('experience_level', models.CharField(choices=[('beginner', 'Iniciante (0-6 meses)'), ('intermediate', 'Intermediário (6-24 meses)'), ('advanced', 'Avançado (2+ anos)'), ('expert', 'Expert/Atleta')], max_length=15)),
                ('training_frequency', models.IntegerField(help_text='Dias por semana')),
                ('available_equipment', models.JSONField(default=list)),
                ('limitations', models.TextField(blank=True)),
                ('preferences', models.JSONField(default=dict)),
                ('last_anamnesis', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AIWorkoutRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_data', models.JSONField()),
                ('confidence_score', models.FloatField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('feedback_rating', models.IntegerField(blank=True, null=True)),
                ('feedback_notes', models.TextField(blank=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_engine.userprofile')),
            ],
        ),
    ]
