# Generated by Django 5.2.1 on 2025-06-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('equipment', models.CharField(choices=[('bodyweight', 'Peso Corporal'), ('dumbbell', 'Halter'), ('barbell', 'Barra'), ('machine', 'Máquina'), ('cable', 'Cabo'), ('kettlebell', 'Kettlebell'), ('resistance_band', 'Faixa Elástica')], max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', 'Iniciante'), ('intermediate', 'Intermediário'), ('advanced', 'Avançado'), ('expert', 'Expert')], max_length=15)),
                ('instructions', models.TextField()),
                ('video_url', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='exercises/')),
                ('is_neural_training', models.BooleanField(default=False, help_text='Exercício para força neural')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('muscle_groups', models.ManyToManyField(related_name='exercises', to='exercises.musclegroup')),
            ],
        ),
    ]
