name: fitai_app
description: "FitAI - Personal Trainer com IA Premium"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI Premium
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  lottie: ^2.7.0
  shimmer: ^3.0.0
  
  # Animations
  animated_text_kit: ^4.2.2
  rive: ^0.12.4
  
  # HTTP & API
  http: ^1.1.0
  dio: ^5.4.0
  
  # State Management
  provider: ^6.1.1
  
  # Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  
  # Navigation
  go_router: ^12.1.3
  
  # Utils
  intl: ^0.19.0
  cached_network_image: ^3.3.0
  
  # Charts & Graphs
  fl_chart: ^0.65.0
  
  # Camera & Media
  camera: ^0.10.5+7
  image_picker: ^1.0.4
  
  # Notifications
  flutter_local_notifications: ^16.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/svg/